Spherical inclusions
tdegeus/GooseFFT pull request #8
Opened 2021-03-26 09:35 UTC by arjunramaswami

Implemented an example to simulate the response of a matrix material with spherical inclusions in which the FFT operations can also be offloaded to the GPU with the help of CuPy

2021-03-27 11:26 UTC, tdegeus commented
Amazing @arjunramaswami and @ahenkes1 I'll review asap!

2021-04-03 14:49 UTC, tdegeus requested changes
Thanks a lot for this example! It is really nice to see how easy it is to use GPUs, and I'm sure it will be appreciated by the community. Furthermore, it is very nice that you took the trouble to vectorize the definition of the projection operator (and to comment it well!).

I made some comments. Beyond them my only concern is the definition of the grid of inclusions. First, I did not understand every detail (see comment), but second, and most important, I think that it should be entirely moved to a function (on top like you did for `create_bin_sphere`). The reason say this is that it is then even easier to read the red-thread, and concern oneself with the problem specific details later. Furthermore, it gives a nice way to split the numerical value of the parameters from the implementation. 

Let me know!!

cc @vondrejc

2021-04-03 14:49 UTC, tdegeus commented on small-strain/spherical-inclusions/linear_elasticity_even.py
> +    import cupy as cp
```suggestion
# True: use GPU computations. False: regular CPU computations
GPU = True
if GPU == False:
    import cupy as cp
```

2021-04-03 14:49 UTC, tdegeus commented on small-strain/spherical-inclusions/linear_elasticity_even.py
> +shape  = [N,N,N]  # number of voxels as list: [Nx,Ny,Nz]
```suggestion
ndof   = ndim**2*N**3 # number of degrees-of-freedom
shape  = [N,N,N]      # number of voxels as list: [Nx,Ny,Nz]
```

2021-04-03 14:49 UTC, tdegeus commented on small-strain/spherical-inclusions/linear_elasticity_even.py
> +if GPU == 1:
```suggestion
if GPU:
```

2021-04-03 14:49 UTC, tdegeus commented on small-strain/spherical-inclusions/linear_elasticity_even.py
> +# phase indicator: spherical inclusions of volume fraction cf
```suggestion
# phase indicator: "nspheres" random spherical inclusions, with total volume fraction "cf"
```

2021-04-03 14:49 UTC, tdegeus commented on small-strain/spherical-inclusions/linear_elasticity_even.py
> +real_cf = np.array([phase[phase == 1].size / phase.size])
That makes no sense here, `phase` just contains zeros

2021-04-03 14:49 UTC, tdegeus commented on small-strain/spherical-inclusions/linear_elasticity_even.py
> +no_of_spheres = 0
```suggestion
nspheres = 0
```

2021-04-03 14:49 UTC, tdegeus commented on small-strain/spherical-inclusions/linear_elasticity_even.py
> +def create_bin_sphere(matrix_size, center, radius):
```suggestion
# function to create a sphere (defined by "center" and "radius") 
# as ones in a grid (defined by "shape") of zeros
def create_bin_sphere(shape, center, radius):
```

2021-04-03 14:49 UTC, tdegeus commented on small-strain/spherical-inclusions/linear_elasticity_even.py
> +print("+--------------------------------------------+")
```suggestion
```
Can be left up to the user, the important thing is to understand the code

2021-04-03 14:49 UTC, tdegeus commented on small-strain/spherical-inclusions/linear_elasticity_even.py
> +        min_r = r
To be honest I'm not entirely sure what is going on here

2021-04-03 14:49 UTC, tdegeus commented on small-strain/spherical-inclusions/linear_elasticity_even.py
> +print("+--------------------------------------------+\n")
```suggestion
```
(same as above)

2021-04-16 10:30 UTC, ahenkes1 commented
@tdegeus by the way, the vectorization of the projection operator was not done by us, I think credits go to @vondrejc  ;)

2021-11-04 09:38 UTC, arjunramaswami commented
HI @tdegeus, are there some other changes required from us for the pull request?

2021-11-15 07:37 UTC, tdegeus commented
Sorry @arjunramaswami . Thanks a lot for your contribution it is highly appreciated! Good luck with the research you do with the code!

2021-11-15 07:37 UTC, merged